/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/home'
import { Route as PlanFilenameRouteImport } from './routes/plan/$filename'
import { Route as DiffReviewAgentInstanceIdRouteImport } from './routes/diff-review/$agentInstanceId'
import { Route as ErrorPagesErrorPageLoadFailedRouteImport } from './routes/_error-pages/error.page-load-failed'

const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanFilenameRoute = PlanFilenameRouteImport.update({
  id: '/plan/$filename',
  path: '/plan/$filename',
  getParentRoute: () => rootRouteImport,
} as any)
const DiffReviewAgentInstanceIdRoute =
  DiffReviewAgentInstanceIdRouteImport.update({
    id: '/diff-review/$agentInstanceId',
    path: '/diff-review/$agentInstanceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ErrorPagesErrorPageLoadFailedRoute =
  ErrorPagesErrorPageLoadFailedRouteImport.update({
    id: '/_error-pages/error/page-load-failed',
    path: '/error/page-load-failed',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/home': typeof HomeRoute
  '/diff-review/$agentInstanceId': typeof DiffReviewAgentInstanceIdRoute
  '/plan/$filename': typeof PlanFilenameRoute
  '/error/page-load-failed': typeof ErrorPagesErrorPageLoadFailedRoute
}
export interface FileRoutesByTo {
  '/home': typeof HomeRoute
  '/diff-review/$agentInstanceId': typeof DiffReviewAgentInstanceIdRoute
  '/plan/$filename': typeof PlanFilenameRoute
  '/error/page-load-failed': typeof ErrorPagesErrorPageLoadFailedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/home': typeof HomeRoute
  '/diff-review/$agentInstanceId': typeof DiffReviewAgentInstanceIdRoute
  '/plan/$filename': typeof PlanFilenameRoute
  '/_error-pages/error/page-load-failed': typeof ErrorPagesErrorPageLoadFailedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/home'
    | '/diff-review/$agentInstanceId'
    | '/plan/$filename'
    | '/error/page-load-failed'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/home'
    | '/diff-review/$agentInstanceId'
    | '/plan/$filename'
    | '/error/page-load-failed'
  id:
    | '__root__'
    | '/home'
    | '/diff-review/$agentInstanceId'
    | '/plan/$filename'
    | '/_error-pages/error/page-load-failed'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomeRoute: typeof HomeRoute
  DiffReviewAgentInstanceIdRoute: typeof DiffReviewAgentInstanceIdRoute
  PlanFilenameRoute: typeof PlanFilenameRoute
  ErrorPagesErrorPageLoadFailedRoute: typeof ErrorPagesErrorPageLoadFailedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/$filename': {
      id: '/plan/$filename'
      path: '/plan/$filename'
      fullPath: '/plan/$filename'
      preLoaderRoute: typeof PlanFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diff-review/$agentInstanceId': {
      id: '/diff-review/$agentInstanceId'
      path: '/diff-review/$agentInstanceId'
      fullPath: '/diff-review/$agentInstanceId'
      preLoaderRoute: typeof DiffReviewAgentInstanceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_error-pages/error/page-load-failed': {
      id: '/_error-pages/error/page-load-failed'
      path: '/error/page-load-failed'
      fullPath: '/error/page-load-failed'
      preLoaderRoute: typeof ErrorPagesErrorPageLoadFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  HomeRoute: HomeRoute,
  DiffReviewAgentInstanceIdRoute: DiffReviewAgentInstanceIdRoute,
  PlanFilenameRoute: PlanFilenameRoute,
  ErrorPagesErrorPageLoadFailedRoute: ErrorPagesErrorPageLoadFailedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
