import { afterEach, describe, expect, it, vi } from 'vitest';
import {
  discoverOpenRouterImageModels,
  generateOpenRouterImage,
} from './openrouter-image-api';

afterEach(() => {
  vi.unstubAllGlobals();
});

describe('OpenRouter image API', () => {
  it('maps discovery capability descriptors', async () => {
    vi.stubGlobal(
      'fetch',
      vi.fn().mockResolvedValue(
        new Response(
          JSON.stringify({
            data: [
              {
                id: 'vendor/image',
                name: 'Image',
                supported_parameters: {
                  resolution: {
                    type: 'enum',
                    values: ['1K', '2K'],
                  },
                  output_compression: {
                    type: 'range',
                  },
                  output_format: {
                    type: 'enum',
                    values: ['png', 'svg'],
                  },
                },
              },
              {
                id: 'vendor/vector-image',
                supported_parameters: {
                  output_format: { type: 'enum', values: ['svg'] },
                },
              },
            ],
          }),
          { status: 200 },
        ),
      ),
    );

    const models = await discoverOpenRouterImageModels(
      'secret',
      'https://openrouter.ai/api/v1',
    );

    expect(models).toEqual([
      expect.objectContaining({
        modelId: 'vendor/image',
        supportedParameters: {
          resolution: ['1K', '2K'],
          output_format: ['png'],
        },
      }),
    ]);
  });

  it('maps common settings and returns generated bytes', async () => {
    const fetchMock = vi.fn().mockResolvedValue(
      new Response(JSON.stringify({ data: [{ b64_json: 'aGVsbG8=' }] }), {
        status: 200,
      }),
    );
    vi.stubGlobal('fetch', fetchMock);

    const result = await generateOpenRouterImage(
      'secret',
      'https://openrouter.ai/api/v1/',
      'vendor/image',
      {
        prompt: 'A red panda astronaut',
        aspectRatio: '16:9',
        resolution: '2K',
        outputFormat: 'png',
      },
    );

    expect(fetchMock).toHaveBeenCalledWith(
      'https://openrouter.ai/api/v1/images',
      expect.objectContaining({
        method: 'POST',
        body: JSON.stringify({
          model: 'vendor/image',
          prompt: 'A red panda astronaut',
          aspect_ratio: '16:9',
          resolution: '2K',
          output_format: 'png',
        }),
      }),
    );
    expect(result.images).toEqual([
      { base64: 'aGVsbG8=', mediaType: 'image/png' },
    ]);
  });
});
