# These templates are heavily inspired by the ones from trpc.io

blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a question
    url: https://discord.gg/gkdGsDYaKA
    about: Ask questions and discuss with other community members on our Discord server
