import type { Patch } from 'immer';

/**
 * Lightweight client-side patch application with structural sharing.
 *
 * Unlike Immer's `applyPatches` (which wraps every call in `produce()`,
 * creating draft proxies and running an O(state_size) finalize walk),
 * this function is O(path_depth) per patch — it only shallow-copies
 * the nodes along the modified path, leaving all siblings as shared
 * references.
 *
 * Only plain objects and arrays are supported (Karton state disallows
 * Map/Set/WeakMap/WeakSet via type constraints).
 */
export function applyPatchesDirect<T>(base: T, patches: Patch[]): T {
  if (patches.length === 0) return base;

  let result: any = base;
  for (const patch of patches) {
    result = applySinglePatch(result, patch);
  }
  return result as T;
}

function shallowCopy(value: any): any {
  if (Array.isArray(value)) return value.slice();
  return Object.assign(Object.create(Object.getPrototypeOf(value)), value);
}

function applySinglePatch(base: any, patch: Patch): any {
  const { op, path, value } = patch as {
    op: Patch['op'];
    path: (string | number)[];
    value: any;
  };

  // Root replacement
  if (path.length === 0) {
    if (op === 'replace') return value;
    // add/remove at root level is not generated by Immer, but handle
    // gracefully by returning value or base respectively.
    return op === 'add' ? value : base;
  }

  // Walk the path, shallow-copying each intermediate node (structural
  // sharing: unchanged siblings keep their original references).
  const root = shallowCopy(base);
  let current = root;

  for (let i = 0; i < path.length - 1; i++) {
    const key = path[i] as string | number;
    current[key] = shallowCopy(current[key]);
    current = current[key];
  }

  // Apply the operation at the leaf
  const lastKey = path[path.length - 1] as string | number;

  switch (op) {
    case 'replace':
      current[lastKey] = value;
      break;

    case 'add':
      if (Array.isArray(current)) {
        if (lastKey === '-') {
          current.push(value);
        } else {
          current.splice(lastKey as number, 0, value);
        }
      } else {
        current[lastKey] = value;
      }
      break;

    case 'remove':
      if (Array.isArray(current)) {
        current.splice(lastKey as number, 1);
      } else {
        delete current[lastKey];
      }
      break;
  }

  return root;
}
